# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/Users/main/Downloads/Radiant-Core-main;/Users/main/Downloads/Radiant-Core-main/macos-release-arm64")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/opt/homebrew/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "radiant-core built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ")
set(CPACK_IGNORE_FILES "/Users/main/Downloads/Radiant-Core-main/.pytest_cache/;/Users/main/Downloads/Radiant-Core-main/.vscode/;/Users/main/Downloads/Radiant-Core-main/build-ninja/;/Users/main/Downloads/Radiant-Core-main/build-release-arm64/;/Users/main/Downloads/Radiant-Core-main/build/;/Users/main/Downloads/Radiant-Core-main/macos-release/;/Users/main/Downloads/Radiant-Core-main/network_monitor.py$;/Users/main/Downloads/Radiant-Core-main/release-builds/;/Users/main/Downloads/Radiant-Core-main/releases/Docker/radiant-core-docker-v2.0.1.tar.gz$;/Users/main/Downloads/Radiant-Core-main/releases/Linux/radiant-core-linux-x64.tar.gz$;/Users/main/Downloads/Radiant-Core-main/"releases/Mac - Apple Silicon/radiant-core-macos-arm64.tar.gz"$;/\\.;/Users/main/Downloads/Radiant-Core-main/macos-release-arm64/;/Users/main/Downloads/Radiant-Core-main/depends/;/Users/main/Downloads/Radiant-Core-main/[^.]+[.]md$;/Users/main/Downloads/Radiant-Core-main/test/cache/;/Users/main/Downloads/Radiant-Core-main/test/lint/;/Users/main/Downloads/Radiant-Core-main/test/sanitizer_suppressions/;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/bitcoind-exit-on-log.sh;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/circular-dependencies.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/copyright_header.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/extract_strings_qt.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/gitian-build.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/optimize-pngs.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/README.md;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/test-security-check.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/update-translations.py;/Users/main/Downloads/Radiant-Core-main/contrib/debian/;/Users/main/Downloads/Radiant-Core-main/contrib/gitian/;/Users/main/Downloads/Radiant-Core-main/contrib/gitian-descriptors/;/Users/main/Downloads/Radiant-Core-main/contrib/qos/;/Users/main/Downloads/Radiant-Core-main/contrib/seeds/;/Users/main/Downloads/Radiant-Core-main/contrib/testgen/;/Users/main/Downloads/Radiant-Core-main/contrib/zmq/;/Users/main/Downloads/Radiant-Core-main/contrib/bitcoin-qt.pro;/Users/main/Downloads/Radiant-Core-main/contrib/gitian-build.py;/Users/main/Downloads/Radiant-Core-main/contrib/README.md;/Users/main/Downloads/Radiant-Core-main/contrib/valgrind.supp")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/Users/main/Downloads/Radiant-Core-main;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/Users/main/Downloads/Radiant-Core-main/cmake/modules")
set(CPACK_MONOLITHIC_INSTALL "ON")
set(CPACK_NSIS_COMPRESSOR "/SOLID lzma")
set(CPACK_NSIS_CONTACT "info@radiantblockchain.org")
set(CPACK_NSIS_CREATE_ICONS_EXTRA "CreateShortCut '$SMPROGRAMS\\$STARTMENU_FOLDER\\Radiant Core (testnet).lnk' '$INSTDIR\\bin\\bitcoin-qt.exe' '-testnet' '$INSTDIR\\bin\\bitcoin-qt.exe' '1'")
set(CPACK_NSIS_DELETE_ICONS_EXTRA "Delete '$SMPROGRAMS\\$START_MENU\\Radiant Core (testnet).lnk'")
set(CPACK_NSIS_DISPLAY_NAME "Radiant Core")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
set(CPACK_NSIS_EXECUTABLES_DIRECTORY "bin")
set(CPACK_NSIS_INSTALLED_ICON_NAME "bin/bitcoin-qt.exe")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MENU_LINKS "bin/bitcoin-qt.exe;Radiant Node")
set(CPACK_NSIS_MUI_FINISHPAGE_RUN "bitcoin-qt.exe")
set(CPACK_NSIS_MUI_ICON "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/bitcoin.ico")
set(CPACK_NSIS_MUI_UNIICON "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/bitcoin.ico")
set(CPACK_NSIS_MUI_UNWELCOMEFINISHPAGE_BITMAP "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/nsis-wizard.bmp")
set(CPACK_NSIS_MUI_WELCOMEFINISHPAGE_BITMAP "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/nsis-wizard.bmp")
set(CPACK_NSIS_PACKAGE_NAME "Radiant Core")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "https://radiantblockchain.org")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/main/Downloads/Radiant-Core-main/macos-release-arm64/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "info@radiantblockchain.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "Radiant Node is a Radiant full node implementation.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/main/Downloads/Radiant-Core-main/doc/README_windows.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Radiant Core is a full node implementation of the Radiant Blockchain protocol, RXD.")
set(CPACK_PACKAGE_FILE_NAME "radiant-core-2.0.0")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://radiantblockchain.org")
set(CPACK_PACKAGE_ICON "/Users/main/Downloads/Radiant-Core-main/share/pixmaps/bitcoin128.png")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "radiant-node")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "radiant-node")
set(CPACK_PACKAGE_NAME "radiant-core")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "")
set(CPACK_PACKAGE_VERSION "2.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/main/Downloads/Radiant-Core-main/COPYING")
set(CPACK_RESOURCE_FILE_README "/opt/homebrew/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/opt/homebrew/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "/Users/main/Downloads/Radiant-Core-main/.pytest_cache/;/Users/main/Downloads/Radiant-Core-main/.vscode/;/Users/main/Downloads/Radiant-Core-main/build-ninja/;/Users/main/Downloads/Radiant-Core-main/build-release-arm64/;/Users/main/Downloads/Radiant-Core-main/build/;/Users/main/Downloads/Radiant-Core-main/macos-release/;/Users/main/Downloads/Radiant-Core-main/network_monitor.py$;/Users/main/Downloads/Radiant-Core-main/release-builds/;/Users/main/Downloads/Radiant-Core-main/releases/Docker/radiant-core-docker-v2.0.1.tar.gz$;/Users/main/Downloads/Radiant-Core-main/releases/Linux/radiant-core-linux-x64.tar.gz$;/Users/main/Downloads/Radiant-Core-main/"releases/Mac - Apple Silicon/radiant-core-macos-arm64.tar.gz"$;/\\.;/Users/main/Downloads/Radiant-Core-main/macos-release-arm64/;/Users/main/Downloads/Radiant-Core-main/depends/;/Users/main/Downloads/Radiant-Core-main/[^.]+[.]md$;/Users/main/Downloads/Radiant-Core-main/test/cache/;/Users/main/Downloads/Radiant-Core-main/test/lint/;/Users/main/Downloads/Radiant-Core-main/test/sanitizer_suppressions/;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/bitcoind-exit-on-log.sh;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/circular-dependencies.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/copyright_header.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/extract_strings_qt.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/gitian-build.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/optimize-pngs.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/README.md;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/test-security-check.py;/Users/main/Downloads/Radiant-Core-main/contrib/devtools/update-translations.py;/Users/main/Downloads/Radiant-Core-main/contrib/debian/;/Users/main/Downloads/Radiant-Core-main/contrib/gitian/;/Users/main/Downloads/Radiant-Core-main/contrib/gitian-descriptors/;/Users/main/Downloads/Radiant-Core-main/contrib/qos/;/Users/main/Downloads/Radiant-Core-main/contrib/seeds/;/Users/main/Downloads/Radiant-Core-main/contrib/testgen/;/Users/main/Downloads/Radiant-Core-main/contrib/zmq/;/Users/main/Downloads/Radiant-Core-main/contrib/bitcoin-qt.pro;/Users/main/Downloads/Radiant-Core-main/contrib/gitian-build.py;/Users/main/Downloads/Radiant-Core-main/contrib/README.md;/Users/main/Downloads/Radiant-Core-main/contrib/valgrind.supp")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/main/Downloads/Radiant-Core-main;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/main/Downloads/Radiant-Core-main/macos-release-arm64/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "radiant-core-2.0.0")
set(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/main/Downloads/Radiant-Core-main/macos-release-arm64/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
